language: python
dist: trusty
sudo: required
python:
  - "2.7"
before_install:
  - pip install awscli
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to build the site
script:
  - cd ./src
  - make s3_upload