language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get install s3cmd
  - pip install -r requirements.txt
# command to build the site
script:
  - cd ./src
  - make s3_upload