language: python
python:
  - "2.7"
before_install:
  - wget http://s3tools.org/repo/deb-all/stable/s3cmd_1.0.0-4_all.deb
  - sudo dpkg -i s3cmd_1.0.0-4_all.deb
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to build the site
script:
  - cd ./src
  - make s3_upload