language: python
dist: trusty
sudo: required
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install s3cmd -qq
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to build the site
script:
  - cd ./src
  - make s3_upload